### PR TITLE
issue #64 - Beautification of post module UI

### PR DESCRIPTION
**Pull request by VBsaini**
added border to text content, box shadow to the posts to tell them apart, used the orange border for the like, dislike and text button and added feature to have a active state for the buttons

image
image
image
image
image

this code is responsive but the navbar is not responsive

Vaibhav saini <vbsaini2004@gmail.com>

### CODE REVIEW

**Review by priyam-03 — CHANGES_REQUESTED** [review]
image
For the first one white shade is not coming
Also Keep Like dislike button under the photos
And please use post.module.css instead of post.css to keep the change only for this file.

**Comment by VBsaini** [comment]
should i remove the changes in post.css then ?

**Comment by priyam-03** [comment]
> should i remove the changes in post.css then ?

You can do that or if you want you can remove that and keep post.module.css but use that in both myPost.js and AllPost.js
Both should have same css linked.

**Comment by VBsaini** [comment]
image
done

**Review by priyam-03 — APPROVED** [review]

**Pull request merged**
