### PR TITLE
added default profile photo

### PR DESCRIPTION
**Pull request by Vinayyy19**
## description 
#42 
added a dummy/default profile image with a condition if user don't upload photo it will display default profile photo

## screenshot
image

## important
please verify from your end before merging and make me know if any problem occured, while i have also verified it's working on my local machine

### CODE REVIEW

**Review by priyam-03 — CHANGES_REQUESTED** [review]
@Vinayyy19 
1. ` The current design lacks proper color coordination, font styling, and spacing, leading to a basic appearance ` Please address this issue. 
2. Also make the profile image properly centered.

**Comment by Vinayyy19** [comment]
hii,
i have commited new changes could you please check now it should center profile photo
image
and about this 
The current design lacks proper color coordination, font styling, and spacing, leading to a basic appearance Please address this issue.
can we create new issue for this,
it's new topic and need to change whole website UI

**Comment by priyam-03** [comment]
> hii, i have commited new changes could you please check now it should center profile photo image and about this The current design lacks proper color coordination, font styling, and spacing, leading to a basic appearance Please address this issue. can we create new issue for this, it's new topic and need to change whole website UI

Here just the welcome name and  email styling color combination and spacing is not visually appealing (which is in this page only), is a new issue required for this?
image
only this part

**Comment by Vinayyy19** [comment]
Oh sorry I thought you are asking for whole website

**Comment by Vinayyy19** [comment]
image
is it as per your expectation ?

**Comment by priyam-03** [comment]
@Vinayyy19 It's okay but ensure the color scheme is appropriately aligned with the overall color combination of the site, also handle cases (alignment part) when name is bigger and not fit in a single line.

**Comment by Vinayyy19** [comment]
yeah i have copied the exact color used in the entire code base

**Comment by Vinayyy19** [comment]
could you check out this now

**Review by priyam-03 — CHANGES_REQUESTED** [review]
1. Make email same color as of name 
2. And you can remove the gradient or make it very minimal

**Comment by Vinayyy19** [comment]
i tried in minimal style but it was too normal so i added blue and white that had been use on whole website that make full website look more good rather than using one color , i think it was good if you'll check full website because it contains all used color at once if still you want we can change it but i'll recommend this is better 
what do you say do we need to change it to minimal design ?
also name and email both are in same style

**Pull request merged**
