### PR TITLE
Fix:mordernizing login and signup page

### LINKED ISSUE #44: Modernizing Login/Signup Pages: Key Suggestions
### Current Challenges:
- Outdated design, color schemes, and fonts.
- Limited mobile responsiveness.

---

### 1. **Color Scheme**:
- Opt for a clean, modern background with vibrant accent colors for buttons and headings.
- Use color to subtly highlight input fields and form interactions.

### 2. **Typography**:
- Switch to modern, sans-serif fonts like Roboto or Open Sans.
- Increase heading sizes and ensure consistent font usage across the page.

### 3. **Layout & Spacing**:
- Ensure a clean, centered layout with ample padding around form fields and buttons.
- Add subtle shadows and borders for a modern touch.

### 4. **Buttons**:
- Introduce rounded corners, smooth hover effects, and larger, more accessible button sizes.
  
### 5. **Responsiveness**:
- Implement mobile-friendly designs, including full-width input fields and optimized scaling with media queries.

## Files :
[Login Page](https://github.com/priyam-03/Recruitify/blob/main/frontend/src/screens/LoginScreen.js)
[Sign Up Page](https://github.com/priyam-03/Recruitify/blob/main/frontend/src/screens/RegisterScreen.js)

## Additional Considerations:
- Add clear form validation messages and feedback.
- Optionally include progress indicators or loading animations for better user experience.

### PR DESCRIPTION
**Pull request by prashantrai-30**
This PR will close #44 :)

### CODE REVIEW

**Review by priyam-03 — CHANGES_REQUESTED** [review]
1. Please ensure the color scheme is appropriately aligned with the overall color combination of the site, avoiding the use of pink tones.
2. Also I think this css is affecting the global css, making changes in other files also like in profile page ig use of login.module.css type of things may resolve this.
image

3. Make the styling of login and signup link appropriate.

**Comment by prashantrai-30** [comment]
Screenshot 2024-10-23 162827
Screenshot 2024-10-23 162841
Is it good now?
And also ig it won't affect global css it might be browser or other issue .

**Comment by priyam-03** [comment]
@prashantrai-30 
Please commit the new change and let me check once.

**Comment by prashantrai-30** [comment]
Hey  @priyam-03 ,
Can you check now?

**Comment by priyam-03** [comment]
> Hey @priyam-03 , Can you check now?

@prashantrai-30 
image

Hey other parts are fine but this issue is still coming in this page, it is not in main branch , or any other branch it is not coming.
Rest is okay. Coming in different browsers also. 
Also you can check your css is applied in update password and update profile page also.


image


So I think this is globally affecting.
In react that's why we use .module.css file types.

**Comment by prashantrai-30** [comment]
Hey @priyam-03,
Can you check now :)

**Review by priyam-03 — CHANGES_REQUESTED** [review]
@prashantrai-30  Change is made only for Login , do for register also.

**Comment by prashantrai-30** [comment]
@priyam-03 you can check now :)

**Review by priyam-03 — APPROVED** [review]
Great Job @prashantrai-30 .

**Comment by priyam-03** [comment]
@prashantrai-30 if you want you can work in this issue also [#43 ](https://github.com/priyam-03/Recruitify/issues/43)
you can make same design for that two pages also.

**Pull request merged**
